language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: 03cbe518-ba51-483d-8323-46cedf36c25a
  app: fast-dawn-42573
  on:
    repo: lemazza/blog-app-mongoose-challenge-solution
    branch: master
services:
- mongodb